### ISSUE TITLE
设置lang

### ISSUE THREAD

**Issue by xuange-like-python** [LoveCards/LoveCardsV2#4]
lang标签用来设置网页所用的语言，这个标签常被浏览器自带的翻译器所引用，但这个项目的lang标签默认为en，导致浏览器总是尝试把中文翻译为中文
(￣△￣；)

**Comment by zhiguai** [comment]
已在[v2.2.0](https://github.com/LoveCards/LoveCardsV2/releases/tag/v2.2.0)修复
