### ISSUE TITLE
写了一篇宝塔安装教程

### ISSUE THREAD

**Issue by NightLamp210** [LoveCards/LoveCardsV2#5]
原文：https://forum.rainyun.com/t/topic/5717/1
希望可以上官方文档
联系：1828202692@qq.com

**Comment by zhiguai** [comment]
> 原文：https://forum.rainyun.com/t/topic/5717/1
> 希望可以上官方文档
> 联系：1828202692@qq.com

好的会尽快加入

**Comment by zhiguai** [comment]
感谢，已经加入文档
